services:
  ChronosApiClientInterface:
    class: Chapi\Component\RemoteClients\ChronosApiClient
    arguments: ["@ChronosHttpClientGuzzle"]

  MarathonApiClientInterface:
    class: Chapi\Component\RemoteClients\MarathonApiClient
    arguments: ["@MarathonHttpClientGuzzle"]