services:
  JobRepositoryChronos:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeChronos"

  JobRepositoryFileSystemChronos:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeFileSystemChronos"

  JobRepositoryFileSystemMarathon:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeFileSystemMarathon"

  JobRepositoryMarathon:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeMarathon"

  JobRepositoryBridgeChronos:
    class: Chapi\Service\JobRepository\BridgeChronos
    arguments:
      - "@ApiClientInterface"
      - "@CacheInterface"
      - "@JobValidatorServiceInterface"
      - "@LoggerInterface"

  JobRepositoryBridgeFileSystemChronos:
    class: Chapi\Service\JobRepository\BridgeFileSystem
    arguments:
      - "@ExternalFileSystemService"
      - "@CacheInterface"
      - "%repository_dir%"

  JobRepositoryBridgeFileSystemMarathon:
    class: Chapi\Service\JobRepository\BridgeFileSystem
    arguments:
      - "@ExternalFileSystemService"
      - "@CacheInterface"
      - "%repository_dir_marathon%"

  JobRepositoryBridgeMarathon:
    class: Chapi\Service\JobRepository\BridgeMarathon


  JobEntityValidatorServiceInterface:
    class: Chapi\Service\JobRepository\JobEntityValidatorService
    arguments:
      - "@DatePeriodFactoryInterface"

  ExternalFileSystemService:
    class: \Symfony\Component\Filesystem\Filesystem