services:
  JobRepositoryChronos:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeChronos"

  JobRepositoryFileSystem:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeFileSystem"

  JobRepositoryMarathon:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeMarathon"

  JobRepositoryBridgeChronos:
    class: Chapi\Service\JobRepository\BridgeChronos
    arguments:
      - "@ApiClientInterface"
      - "@CacheInterface"
      - "@JobValidatorServiceInterface"
      - "@LoggerInterface"

  JobRepositoryBridgeFileSystem:
    class: Chapi\Service\JobRepository\BridgeFileSystem
    arguments:
      - "@ExternalFileSystemService"
      - "@CacheInterface"
      - "%repository_dir%"

  JobRepositoryBridgeMarathon:
    class: Chapi\Service\JobRepository\BridgeMarathon


  JobEntityValidatorServiceInterface:
    class: Chapi\Service\JobRepository\JobEntityValidatorService
    arguments:
      - "@DatePeriodFactoryInterface"

  ExternalFileSystemService:
    class: \Symfony\Component\Filesystem\Filesystem