services:
  JobDependencyServiceInterface:
      class: Chapi\Service\JobDependencies\JobDependencyService
      arguments:
        - "@JobRepositoryFileSystemChronos"
        - "@JobRepositoryChronos"
