services:
  JobComparisonInterface:
    class: Chapi\BusinessCase\Comparison\JobComparisonBusinessCase
    arguments:
      - "@JobRepositoryFileSystemChronos"
      - "@JobRepositoryFileSystemMarathon"
      - "@JobRepositoryChronos"
      - "@JobRepositoryMarathon"
      - "@DiffCompareInterface"
      - "@DatePeriodFactoryInterface"
      - "@LoggerInterface"