services:
  JobComparisonInterface:
    class: Chapi\BusinessCase\Comparison\CompositeJobComparisonBusinessCase
    calls:
      - [AddComparisionCases, ["@ChronosJobComparisionBusinessCase"]]
      - [AddComparisionCases, ["@MarathonJobComparisionBusinessCase"]]

  ChronosJobComparisionBusinessCase:
    class: Chapi\BusinessCase\Comparison\ChronosJobComparisonBusinessCase
    arguments:
      - "@JobRepositoryFileSystemChronos"
      - "@JobRepositoryFileSystemMarathon"
      - "@JobRepositoryChronos"
      - "@JobRepositoryMarathon"
      - "@DiffCompareInterface"
      - "@DatePeriodFactoryInterface"
      - "@LoggerInterface"

  MarathonJobComparisionBusinessCase:
    class: Chapi\BusinessCase\Comparison\MarathonJobComparisonBusinessCase
    arguments:
      - "@JobRepositoryFileSystemMarathon"
      - "@JobRepositoryMarathon"
      - "@DiffCompareInterface"