services:
  StoreJobBusinessCaseInterface:
    class: Chapi\BusinessCase\JobManagement\StoreJobBusinessCase
    arguments:
      - "@JobIndexServiceInterface"
      - "@JobRepositoryChronos"
      - "@JobRepositoryFileSystemChronos"
      - "@ChronosJobComparisionBusinessCase"
      - "@JobDependencyServiceInterface"
      - "@LoggerInterface"


  MarathonStoreBusinessCase:
    class: Chapi\BusinessCase\JobManagement\MarathonStoreJobBusinessCase
    arguments:
      - "@JobIndexServiceInterface"
      - "@JobRepositoryMarathon"
      - "@JobRepositoryFileSystemMarathon"
      - "@MarathonJobComparisionBusinessCase"
      - "@LoggerInterface"


  StoreJobBusinessCaseFactoryInterface:
    class: Chapi\BusinessCase\JobManagement\StoreJobBusinessCaseFactory
    calls:
      - [addBusinesCase, ["@StoreJobBusinessCaseInterface"]]
      - [addBusinesCase, ["@MarathonStoreBusinessCase"]]
